<table align="center" bgcolor="#005a95" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse !important;display:table;font-family:'helvetica' , 'arial' , sans-serif !important;min-width:100%;table-layout:fixed !important"><tbody><tr><td align="center" bgcolor="#005a95" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important">
            <table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;max-width:640px;width:100%"><tbody><tr><td align="center" bgcolor="#005a95" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important">
                        <table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;max-width:580px;width:100%"><tbody><tr><td height="50" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:50px;line-height:50px">&nbsp;</td></tr><tr><td style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important"><table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;width:440px"><tbody><tr><td align="center" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important">
                                                <h1 style="color:#fff">AMZ Reviews intense</h1>
                                            </td></tr></tbody></table></td></tr><tr><td height="50" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:50px;line-height:50px">&nbsp;</td></tr></tbody></table>
                    </td></tr></tbody></table>
        </td></tr></tbody></table>
<div>
    <table align="center" bgcolor="#005a95" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse !important;display:table;font-family:'helvetica' , 'arial' , sans-serif !important;min-width:100%;table-layout:fixed !important"><tbody><tr><td align="center" bgcolor="#005a95" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important">
                <table align="center" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;max-width:640px;width:100%"><tbody><tr><td height="20" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:20px;line-height:20px">&nbsp;</td></tr><tr><td align="center" bgcolor="#ffffff" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important">
                            <table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;max-width:580px;width:100%"><tbody><tr><td height="20" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:20px;line-height:20px">&nbsp;</td></tr><tr><td align="left" style="border-collapse:collapse !important;color:#000000;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:34px;font-weight:bold;line-height:39px">
                                        Здравствуйте, ${name}!
                                    </td></tr><tr><td height="15" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:15px;line-height:15px">&nbsp;</td></tr></tbody></table>
                        </td></tr></tbody></table>
            </td></tr></tbody></table>
</div>
<div>
    <table align="center" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse !important;display:table;font-family:'helvetica' , 'arial' , sans-serif !important;min-width:100%;table-layout:fixed !important"><tbody><tr><td align="center" bgcolor="#ffffff" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important">
                <table align="center" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;max-width:640px;width:100%"><tbody><tr><td align="center" bgcolor="#ffffff" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important">
                            <table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;max-width:580px;width:100%"><tbody><tr><td align="left" style="border-collapse:collapse !important;color:#000000;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:22px;line-height:27px"></td></tr><tr><td height="20" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:20px;line-height:20px">&nbsp;</td></tr><tr><td height="10" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:10px;line-height:10px">&nbsp;</td></tr></tbody></table>
                        </td></tr></tbody></table>
            </td></tr></tbody></table>
</div>
<div>
    <table align="center" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse !important;display:table;font-family:'helvetica' , 'arial' , sans-serif !important;min-width:100%;table-layout:fixed !important"><tbody><tr><td align="center" bgcolor="#ffffff" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important">
                <table align="center" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;max-width:640px;width:100%"><tbody><tr><td align="center" bgcolor="#ffffff" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important">
                            <table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;max-width:580px;width:100%"><tbody><tr><td height="15" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:15px;line-height:15px">&nbsp;</td></tr><tr><td align="left" style="border-collapse:collapse !important;color:#000000;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:16px;line-height:21px">
                                        Благодарим Вас за регистрацию на сайте <a href="https://amzreviews.herokuapp.com">amzreviews.herokuapp.com.</a><br><br>

                                        В целях защиты Ваших персональных данных, для входа в личный кабинет используйте логин и пароль, указанные при регистрации.
                                    </td></tr><tr><td height="20" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:20px;line-height:20px">&nbsp;</td></tr><tr><td align="left" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important">
                                        <table align="left" bgcolor="#ff9900" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse !important;border-radius:6px;font-family:'helvetica' , 'arial' , sans-serif !important"><tbody><tr><td height="15" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:15px;line-height:15px">&nbsp;</td></tr><tr><td align="center" style="border-collapse:collapse !important;color:#ffffff;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:16px;line-height:21px;padding:0px 20px 0px 20px;text-align:center">
                                                    <a href="https://amzreviews.herokuapp.com/confirm-account/${token}" style="color:#ffffff;text-decoration:none" rel="noopener noreferrer">
                                                        <b>ПОДТВЕРДИТЬ E-MAIL</b></a>
                                                </td></tr><tr><td height="15" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:15px;line-height:15px">&nbsp;</td></tr></tbody></table>
                                    </td></tr><tr><td height="15" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:15px;line-height:15px">&nbsp;</td></tr></tbody></table>
                        </td></tr></tbody></table>
            </td></tr></tbody></table>
</div>
<div>
    <table align="center" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0"  width="100%" style="border-collapse:collapse !important;display:table;font-family:'helvetica' , 'arial' , sans-serif !important;min-width:100%;table-layout:fixed !important"><tbody><tr><td align="center" bgcolor="#ffffff" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important">
                <table align="center" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;max-width:640px;width:100%"><tbody><tr><td align="center" bgcolor="#ffffff" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important">
                            <table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;max-width:580px;width:100%"><tbody><tr><td height="15" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:15px;line-height:15px">&nbsp;</td></tr><tr><td align="left" style="border-collapse:collapse !important;color:#000000;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:16px;line-height:21px">
                                        Если Вы не ожидали получения этого письма или считаете, что получили его по ошибке, свяжитесь с нами.
                                    </td></tr><tr><td height="20" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:20px;line-height:20px">&nbsp;</td></tr></tbody></table>
                        </td></tr></tbody></table>
            </td></tr></tbody></table>
</div>
<div>
    <table align="center" bgcolor="#f2f2f3" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse !important;display:table;font-family:'helvetica' , 'arial' , sans-serif !important;min-width:100%;table-layout:fixed !important"><tbody><tr><td align="center" bgcolor="#f2f2f3" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important">
                <table align="center" bgcolor="#f2f2f3" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;max-width:640px;width:100%"><tbody><tr><td align="center" bgcolor="#f2f2f3" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important">
                            <table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;max-width:580px;width:100%"><tbody><tr><td height="10" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:10px;line-height:10px">&nbsp;</td></tr><tr><td align="left" style="border-collapse:collapse !important;color:#000000;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:9px;line-height:18px">
                                    </td></tr><tr><td align="left" style="border-collapse:collapse !important;color:#000000;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:11px;line-height:18px">
                                    </td></tr><tr><td height="10" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:10px;line-height:10px">&nbsp;</td></tr><tr><td align="left" style="border-collapse:collapse !important;color:#000000;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:11px;line-height:18px">
                                        <p style="margin-bottom:0 !important;margin-left:0 !important;margin-right:0 !important;margin-top:0 !important;padding-bottom:0 !important;padding-left:0 !important;padding-right:0 !important;padding-top:0 !important">© 2006-
                                            2019, Inc. or its affiliates. All rights reserved. Amazon, Amazon Advertising, Amazon.com, and the Amazon logo are registered trademarks of Amazon.com, Inc. or its affiliates. Amazon.com, 410 Terry Avenue, Seattle, WA <span class="wmi-callto">98109-5210</span>.
                                            <br>
                                            We hope you found this message to be useful. However, if you'd rather not receive future e-mails of this sort from Amazon Services, please.
                                        </p>
                                    </td></tr><tr><td height="20" style="border-collapse:collapse !important;font-family:'helvetica' , 'arial' , sans-serif !important;font-size:20px;line-height:20px">&nbsp;</td></tr></tbody></table>
                        </td></tr></tbody></table>
            </td></tr></tbody>
    </table>
</div>