DROP TABLE IF EXISTS articles;

CREATE TABLE articles
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date                TIMESTAMP                NOT NULL,
    name                VARCHAR                  NOT NULL,
    description_ru      VARCHAR                  NOT NULL,
    description_us      VARCHAR                  NOT NULL,
    keywords_ru         VARCHAR                  NOT NULL,
    keywords_us         VARCHAR                  NOT NULL,
    headline_ru         VARCHAR                  NOT NULL,
    headline_us         VARCHAR                  NOT NULL,
    text_ru             VARCHAR                  NOT NULL,
    text_us             VARCHAR                  NOT NULL
);
CREATE UNIQUE INDEX article_ru_unique_name_idx ON articles (name);