DROP TABLE IF EXISTS confirm_tokens;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS users;

CREATE TABLE users
(
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR                     NOT NULL,
  date         TIMESTAMP                   NOT NULL,
  email        VARCHAR                     NOT NULL,
  password     VARCHAR                     NOT NULL,
  enabled      BOOL DEFAULT TRUE           NOT NULL,
  paypal       VARCHAR                     NULL,
  country      VARCHAR                     NOT NULL,
  balance      INTEGER DEFAULT 0           NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx ON users (email);

CREATE TABLE user_roles
(
  user_id      INTEGER        NOT NULL,
  role         VARCHAR,
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

CREATE TABLE confirm_tokens
(
  id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date                     TIMESTAMP          NOT NULL,
  confirm_token            VARCHAR            NOT NULL,
  user_id                  INTEGER            NOT NULL,
  FOREIGN KEY (user_id) REFERENCES USERS (id)
);
CREATE UNIQUE INDEX token_unique_user_idx ON confirm_tokens (confirm_token);

CREATE TABLE products
(
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                VARCHAR                     NOT NULL,
  date                TIMESTAMP                   NOT NULL,
  date_of_change      TIMESTAMP                   NULL,
  asin                VARCHAR                     NOT NULL,
  title               VARCHAR                     NOT NULL,
  image               VARCHAR                     NOT NULL,
  price               DOUBLE PRECISION            NOT NULL,
  description         VARCHAR                     NOT NULL,
  key                 VARCHAR                     NULL,
  review_enable       BOOL                        NULL,
  count_orders        INTEGER DEFAULT 0           NOT NULL,
  active_orders       INTEGER DEFAULT 0           NOT NULL,
  completed_orders    INTEGER DEFAULT 0           NOT NULL,
  user_id             INTEGER                     NOT NULL,
  FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX products_unique_asin ON products (asin);

CREATE TABLE orders
(
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date            TIMESTAMP                NOT NULL,
  name            VARCHAR                  NOT NULL,
  price           DOUBLE PRECISION         NOT NULL,
  status          VARCHAR                  NOT NULL,
  payment         VARCHAR                  NOT NULL,
  key             VARCHAR                  NOT NULL,
  review_enable   BOOL DEFAULT FALSE       NOT NULL,
  reviews         VARCHAR                  NULL,
  refund          BOOL                     NOT NULL,
  order_id        VARCHAR                  NULL,
  user_id         INTEGER                  NULL,
  product_id      INTEGER                  NOT NULL,
  FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES PRODUCTS (id) ON DELETE CASCADE
);

CREATE TABLE images
(
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url             VARCHAR               NOT NULL,
  product_id      INTEGER               NOT NULL,
  FOREIGN KEY (product_id) REFERENCES PRODUCTS (id) ON DELETE CASCADE
);